In [2]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
import numpy as np
print('Packages installed Successfully ✅')

Packages installed Successfully ✅

**Loading Data**

In [5]:
df = pd.read_csv('heart_disease_dataset.csv')
print('Data import successfuly ✅')
df.head()

Data import successfuly ✅

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,Male,204,165,62,Current,NaN,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,Female,192,90,72,Current,NaN,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,Female,172,163,93,Never,NaN,6,No,Yes,No,2,183,Yes,Asymptomatic,0

**EDA**

In [6]:
#Cat to int
df = pd.get_dummies(df, columns=["Gender"],dtype=int)
df = pd.get_dummies(df, columns=["Chest Pain Type"],dtype=int)
df = pd.get_dummies(df, columns=['Smoking'], dtype=int)

#Numeric Columns
num_cols = df.select_dtypes(include=['int64','float64'])
for col in num_cols:
  df[col] = df[col].fillna(df[col].median())

#Cat to int
df['Alcohol Intake'] = df['Alcohol Intake'].fillna(df['Alcohol Intake'].mode()[0])
df = pd.get_dummies(df, columns=['Alcohol Intake'], dtype=int)

#bool to int
boolen_cols = df.select_dtypes(include=['object'])
for col in boolen_cols:
  df = pd.get_dummies(df, columns=[col], dtype=int)

df.head()

,Age,Cholesterol,Blood Pressure,Heart Rate,Exercise Hours,Stress Level,Blood Sugar,Heart Disease,Gender_Female,Gender_Male,...,Alcohol Intake_Heavy,Alcohol Intake_Moderate,Family History_No,Family History_Yes,Diabetes_No,Diabetes_Yes,Obesity_No,Obesity_Yes,Exercise Induced Angina_No,Exercise Induced Angina_Yes
0,75,228,119,66,1,8,119,1,1,0,...,1,0,1,0,1,0,0,1,0,1
1,48,204,165,62,5,9,70,0,0,1,...,1,0,1,0,1,0,1,0,0,1
2,53,234,91,67,3,5,196,1,0,1,...,1,0,0,1,1,0,0,1,0,1
3,69,192,90,72,4,7,107,0,1,0,...,1,0,1,0,0,1,1,0,0,1
4,62,172,163,93,6,2,183,0,1,0,...,1,0,1,0,0,1,1,0,0,1

In [7]:
#Check is there any null
df.isnull().sum()
print( 'No Null or Empty Value in Data set 🔥' if (df.isnull().sum().sum()==0) else 'Null Value present please clear it' )

No Null or Empty Value in Data set 🔥

**Split The Train & Test Data**

In [8]:
X = df.drop(columns=['Heart Disease']).values
y = df['Heart Disease'].values

X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f'Shape of X: {X.shape}')
print(f'Shape of y: {y.shape}')

Shape of X: (1000, 26)
Shape of y: (1000,)

Model Train & Accuracy

In [9]:
model = Sequential([
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(16, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.summary()

model.compile(
    loss='binary_crossentropy',
    optimizer=Adam(learning_rate=0.0003),
    metrics=["accuracy"]
)
print("\nModel compiled! ✅")

history = model.fit(
    X_train,y_train,epochs=150,batch_size=15, validation_split=0.2,
)
print("\nTraining complete! ✅")

loss, accuracy = model.evaluate(X_test, y_test, batch_size=10, verbose=1)
print(f'Loss value :{loss}')
print(f'Accuracy Value: {accuracy*100:.2f}%')

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ ?                      │   0 (unbuilt) │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ ?                      │   0 (unbuilt) │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ ?                      │   0 (unbuilt) │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Model compiled! ✅
Epoch 1/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 12s 30ms/step - accuracy: 0.4969 - loss: 0.8936 - val_accuracy: 0.5063 - val_loss: 0.7032
Epoch 2/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.5078 - loss: 0.8822 - val_accuracy: 0.5813 - val_loss: 0.6877
Epoch 3/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5359 - loss: 0.8392 - val_accuracy: 0.6062 - val_loss: 0.6828
Epoch 4/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5234 - loss: 0.8059 - val_accuracy: 0.6687 - val_loss: 0.6694
Epoch 5/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5406 - loss: 0.7791 - val_accuracy: 0.6250 - val_loss: 0.6646
Epoch 6/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.5500 - loss: 0.7639 - val_accuracy: 0.6375 - val_loss: 0.6574
Epoch 7/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.6125 - loss: 0.6945 - val_accuracy: 0.6438 - val_loss: 0.6526
Epoch 8/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5953 - loss: 0.7255 - val_accuracy: 0.6500 - val_loss: 0.6443
Epoch 9/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6062 - loss: 0.6914 - val_accuracy: 0.6562 - val_loss: 0.6370
Epoch 10/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6094 - loss: 0.6811 - val_accuracy: 0.6750 - val_loss: 0.6285
Epoch 11/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6187 - loss: 0.6762 - val_accuracy: 0.6938 - val_loss: 0.6192
Epoch 12/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6047 - loss: 0.6817 - val_accuracy: 0.7063 - val_loss: 0.6110
Epoch 13/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6438 - loss: 0.6810 - val_accuracy: 0.7125 - val_loss: 0.6013
Epoch 14/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6422 - loss: 0.6633 - val_accuracy: 0.7188 - val_loss: 0.5951
Epoch 15/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6219 - loss: 0.6589 - val_accuracy: 0.7125 - val_loss: 0.5865
Epoch 16/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6078 - loss: 0.6637 - val_accuracy: 0.7312 - val_loss: 0.5796
Epoch 17/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6516 - loss: 0.6395 - val_accuracy: 0.7437 - val_loss: 0.5689
Epoch 18/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6516 - loss: 0.6275 - val_accuracy: 0.7625 - val_loss: 0.5576
Epoch 19/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6344 - loss: 0.6387 - val_accuracy: 0.7688 - val_loss: 0.5502
Epoch 20/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6828 - loss: 0.6051 - val_accuracy: 0.7750 - val_loss: 0.5428
Epoch 21/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6891 - loss: 0.5986 - val_accuracy: 0.7750 - val_loss: 0.5370
Epoch 22/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6766 - loss: 0.6054 - val_accuracy: 0.7750 - val_loss: 0.5255
Epoch 23/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7047 - loss: 0.5781 - val_accuracy: 0.7937 - val_loss: 0.5190
Epoch 24/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6953 - loss: 0.5965 - val_accuracy: 0.7937 - val_loss: 0.5108
Epoch 25/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6891 - loss: 0.5858 - val_accuracy: 0.8125 - val_loss: 0.5021
Epoch 26/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7281 - loss: 0.5384 - val_accuracy: 0.8062 - val_loss: 0.4909
Epoch 27/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7156 - loss: 0.5645 - val_accuracy: 0.8250 - val_loss: 0.4827
Epoch 28/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6875 - loss: 0.5456 - val_accuracy: 0.8313 - val_loss: 0.4717
Epoch 29/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7266 - loss: 0.5359 - val_accuracy: 0.8375 - val_loss: 0.4639
Epoch 30/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7219 - loss: 0.5328 - val_accuracy: 0.8188 - val_loss: 0.4527
Epoch 31/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7453 - loss: 0.5374 - val_accuracy: 0.8188 - val_loss: 0.4428
Epoch 32/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7219 - loss: 0.5309 - val_accuracy: 0.8125 - val_loss: 0.4344
Epoch 33/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7672 - loss: 0.5062 - val_accuracy: 0.8125 - val_loss: 0.4262
Epoch 34/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7766 - loss: 0.4715 - val_accuracy: 0.8250 - val_loss: 0.4165
Epoch 35/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7594 - loss: 0.5065 - val_accuracy: 0.8313 - val_loss: 0.4051
Epoch 36/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7734 - loss: 0.5130 - val_accuracy: 0.8500 - val_loss: 0.3996
Epoch 37/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7781 - loss: 0.4612 - val_accuracy: 0.8562 - val_loss: 0.3903
Epoch 38/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7625 - loss: 0.4806 - val_accuracy: 0.8625 - val_loss: 0.3845
Epoch 39/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7922 - loss: 0.4514 - val_accuracy: 0.8687 - val_loss: 0.3799
Epoch 40/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7844 - loss: 0.4521 - val_accuracy: 0.8750 - val_loss: 0.3724
Epoch 41/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7922 - loss: 0.4518 - val_accuracy: 0.8687 - val_loss: 0.3641
Epoch 42/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7875 - loss: 0.4608 - val_accuracy: 0.8625 - val_loss: 0.3579
Epoch 43/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8047 - loss: 0.4496 - val_accuracy: 0.8813 - val_loss: 0.3511
Epoch 44/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8391 - loss: 0.3991 - val_accuracy: 0.8875 - val_loss: 0.3406
Epoch 45/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.4099 - val_accuracy: 0.8813 - val_loss: 0.3349
Epoch 46/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8109 - loss: 0.4183 - val_accuracy: 0.8813 - val_loss: 0.3291
Epoch 47/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8266 - loss: 0.3868 - val_accuracy: 0.8875 - val_loss: 0.3250
Epoch 48/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4228 - val_accuracy: 0.9000 - val_loss: 0.3192
Epoch 49/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8219 - loss: 0.4197 - val_accuracy: 0.8938 - val_loss: 0.3150
Epoch 50/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8172 - loss: 0.4106 - val_accuracy: 0.8938 - val_loss: 0.3126
Epoch 51/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8141 - loss: 0.4137 - val_accuracy: 0.8938 - val_loss: 0.3107
Epoch 52/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8047 - loss: 0.4287 - val_accuracy: 0.8938 - val_loss: 0.3103
Epoch 53/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8234 - loss: 0.3992 - val_accuracy: 0.9000 - val_loss: 0.3102
Epoch 54/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8125 - loss: 0.3945 - val_accuracy: 0.8938 - val_loss: 0.3061
Epoch 55/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.3889 - val_accuracy: 0.8938 - val_loss: 0.3032
Epoch 56/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8141 - loss: 0.4125 - val_accuracy: 0.8875 - val_loss: 0.3037
Epoch 57/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8375 - loss: 0.3607 - val_accuracy: 0.8875 - val_loss: 0.3001
Epoch 58/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8438 - loss: 0.3735 - val_accuracy: 0.8875 - val_loss: 0.2971
Epoch 59/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8531 - loss: 0.3508 - val_accuracy: 0.8875 - val_loss: 0.2939
Epoch 60/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8297 - loss: 0.3821 - val_accuracy: 0.8875 - val_loss: 0.2888
Epoch 61/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8328 - loss: 0.3789 - val_accuracy: 0.8875 - val_loss: 0.2870
Epoch 62/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8375 - loss: 0.3665 - val_accuracy: 0.8875 - val_loss: 0.2848
Epoch 63/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8344 - loss: 0.3509 - val_accuracy: 0.8875 - val_loss: 0.2813
Epoch 64/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8469 - loss: 0.3444 - val_accuracy: 0.8875 - val_loss: 0.2770
Epoch 65/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8406 - loss: 0.3619 - val_accuracy: 0.8813 - val_loss: 0.2827
Epoch 66/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8422 - loss: 0.3634 - val_accuracy: 0.8813 - val_loss: 0.2802
Epoch 67/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3513 - val_accuracy: 0.8875 - val_loss: 0.2756
Epoch 68/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8406 - loss: 0.3932 - val_accuracy: 0.8875 - val_loss: 0.2745
Epoch 69/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8641 - loss: 0.3319 - val_accuracy: 0.8813 - val_loss: 0.2768
Epoch 70/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3545 - val_accuracy: 0.8813 - val_loss: 0.2734
Epoch 71/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8531 - loss: 0.3470 - val_accuracy: 0.8687 - val_loss: 0.2738
Epoch 72/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8422 - loss: 0.3562 - val_accuracy: 0.8813 - val_loss: 0.2730
Epoch 73/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8344 - loss: 0.3520 - val_accuracy: 0.8750 - val_loss: 0.2738
Epoch 74/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8578 - loss: 0.3442 - val_accuracy: 0.8813 - val_loss: 0.2726
Epoch 75/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8734 - loss: 0.3105 - val_accuracy: 0.8813 - val_loss: 0.2708
Epoch 76/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.3272 - val_accuracy: 0.8813 - val_loss: 0.2684
Epoch 77/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8766 - loss: 0.2972 - val_accuracy: 0.8750 - val_loss: 0.2693
Epoch 78/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8359 - loss: 0.3226 - val_accuracy: 0.8813 - val_loss: 0.2702
Epoch 79/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8687 - loss: 0.3188 - val_accuracy: 0.8813 - val_loss: 0.2705
Epoch 80/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8813 - loss: 0.3025 - val_accuracy: 0.8813 - val_loss: 0.2666
Epoch 81/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8703 - loss: 0.2963 - val_accuracy: 0.8875 - val_loss: 0.2655
Epoch 82/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8500 - loss: 0.3370 - val_accuracy: 0.8813 - val_loss: 0.2669
Epoch 83/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8609 - loss: 0.3301 - val_accuracy: 0.8813 - val_loss: 0.2674
Epoch 84/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.2965 - val_accuracy: 0.8875 - val_loss: 0.2637
Epoch 85/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8594 - loss: 0.3321 - val_accuracy: 0.8938 - val_loss: 0.2590
Epoch 86/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8547 - loss: 0.3386 - val_accuracy: 0.8938 - val_loss: 0.2610
Epoch 87/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8719 - loss: 0.2890 - val_accuracy: 0.8938 - val_loss: 0.2592
Epoch 88/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8766 - loss: 0.2918 - val_accuracy: 0.8938 - val_loss: 0.2553
Epoch 89/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8375 - loss: 0.3396 - val_accuracy: 0.9000 - val_loss: 0.2531
Epoch 90/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8594 - loss: 0.2992 - val_accuracy: 0.9062 - val_loss: 0.2504
Epoch 91/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.3240 - val_accuracy: 0.9125 - val_loss: 0.2511
Epoch 92/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8859 - loss: 0.2843 - val_accuracy: 0.9062 - val_loss: 0.2464
Epoch 93/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9062 - loss: 0.2832 - val_accuracy: 0.9000 - val_loss: 0.2447
Epoch 94/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8766 - loss: 0.2858 - val_accuracy: 0.8938 - val_loss: 0.2449
Epoch 95/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8938 - loss: 0.2561 - val_accuracy: 0.8938 - val_loss: 0.2456
Epoch 96/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.3077 - val_accuracy: 0.8938 - val_loss: 0.2453
Epoch 97/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8516 - loss: 0.3250 - val_accuracy: 0.9000 - val_loss: 0.2420
Epoch 98/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - loss: 0.3033 - val_accuracy: 0.9000 - val_loss: 0.2417
Epoch 99/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2697 - val_accuracy: 0.9000 - val_loss: 0.2422
Epoch 100/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8719 - loss: 0.3029 - val_accuracy: 0.8938 - val_loss: 0.2434
Epoch 101/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8828 - loss: 0.2557 - val_accuracy: 0.8938 - val_loss: 0.2439
Epoch 102/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8906 - loss: 0.2631 - val_accuracy: 0.9000 - val_loss: 0.2431
Epoch 103/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - loss: 0.2871 - val_accuracy: 0.9062 - val_loss: 0.2398
Epoch 104/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8844 - loss: 0.2961 - val_accuracy: 0.9062 - val_loss: 0.2399
Epoch 105/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8734 - loss: 0.2966 - val_accuracy: 0.9062 - val_loss: 0.2400
Epoch 106/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8844 - loss: 0.2706 - val_accuracy: 0.9000 - val_loss: 0.2364
Epoch 107/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8844 - loss: 0.2735 - val_accuracy: 0.9062 - val_loss: 0.2380
Epoch 108/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8656 - loss: 0.2756 - val_accuracy: 0.9062 - val_loss: 0.2363
Epoch 109/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8813 - loss: 0.2712 - val_accuracy: 0.9062 - val_loss: 0.2329
Epoch 110/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8859 - loss: 0.2760 - val_accuracy: 0.9062 - val_loss: 0.2325
Epoch 111/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2565 - val_accuracy: 0.9125 - val_loss: 0.2349
Epoch 112/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8969 - loss: 0.2864 - val_accuracy: 0.9125 - val_loss: 0.2344
Epoch 113/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8984 - loss: 0.2452 - val_accuracy: 0.9125 - val_loss: 0.2356
Epoch 114/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - loss: 0.2862 - val_accuracy: 0.9062 - val_loss: 0.2340
Epoch 115/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8953 - loss: 0.2466 - val_accuracy: 0.9125 - val_loss: 0.2300
Epoch 116/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8875 - loss: 0.2667 - val_accuracy: 0.9125 - val_loss: 0.2311
Epoch 117/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8922 - loss: 0.2669 - val_accuracy: 0.9125 - val_loss: 0.2322
Epoch 118/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8813 - loss: 0.2813 - val_accuracy: 0.9125 - val_loss: 0.2315
Epoch 119/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9078 - loss: 0.2201 - val_accuracy: 0.9125 - val_loss: 0.2258
Epoch 120/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.2828 - val_accuracy: 0.9187 - val_loss: 0.2252
Epoch 121/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8859 - loss: 0.2804 - val_accuracy: 0.9125 - val_loss: 0.2268
Epoch 122/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8672 - loss: 0.3062 - val_accuracy: 0.9125 - val_loss: 0.2276
Epoch 123/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8813 - loss: 0.2739 - val_accuracy: 0.9062 - val_loss: 0.2251
Epoch 124/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8813 - loss: 0.2572 - val_accuracy: 0.9125 - val_loss: 0.2254
Epoch 125/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8891 - loss: 0.2766 - val_accuracy: 0.9187 - val_loss: 0.2229
Epoch 126/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9141 - loss: 0.2376 - val_accuracy: 0.9187 - val_loss: 0.2220
Epoch 127/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8859 - loss: 0.2530 - val_accuracy: 0.9187 - val_loss: 0.2258
Epoch 128/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8813 - loss: 0.2628 - val_accuracy: 0.9187 - val_loss: 0.2215
Epoch 129/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.2866 - val_accuracy: 0.9187 - val_loss: 0.2168
Epoch 130/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9094 - loss: 0.2300 - val_accuracy: 0.9187 - val_loss: 0.2156
Epoch 131/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9047 - loss: 0.2562 - val_accuracy: 0.9250 - val_loss: 0.2167
Epoch 132/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8906 - loss: 0.2364 - val_accuracy: 0.9250 - val_loss: 0.2130
Epoch 133/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8891 - loss: 0.2519 - val_accuracy: 0.9250 - val_loss: 0.2128
Epoch 134/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9031 - loss: 0.2351 - val_accuracy: 0.9312 - val_loss: 0.2129
Epoch 135/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8953 - loss: 0.2386 - val_accuracy: 0.9312 - val_loss: 0.2135
Epoch 136/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8906 - loss: 0.2658 - val_accuracy: 0.9250 - val_loss: 0.2156
Epoch 137/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9016 - loss: 0.2609 - val_accuracy: 0.9187 - val_loss: 0.2197
Epoch 138/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2686 - val_accuracy: 0.9187 - val_loss: 0.2161
Epoch 139/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2318 - val_accuracy: 0.9187 - val_loss: 0.2164
Epoch 140/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9094 - loss: 0.2303 - val_accuracy: 0.9187 - val_loss: 0.2162
Epoch 141/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8953 - loss: 0.2482 - val_accuracy: 0.9187 - val_loss: 0.2178
Epoch 142/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9000 - loss: 0.2354 - val_accuracy: 0.9187 - val_loss: 0.2158
Epoch 143/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9031 - loss: 0.2356 - val_accuracy: 0.9187 - val_loss: 0.2176
Epoch 144/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9000 - loss: 0.2093 - val_accuracy: 0.9187 - val_loss: 0.2137
Epoch 145/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9172 - loss: 0.2427 - val_accuracy: 0.9187 - val_loss: 0.2157
Epoch 146/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9094 - loss: 0.2287 - val_accuracy: 0.9250 - val_loss: 0.2132
Epoch 147/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8953 - loss: 0.2486 - val_accuracy: 0.9312 - val_loss: 0.2087
Epoch 148/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9109 - loss: 0.2391 - val_accuracy: 0.9312 - val_loss: 0.2070
Epoch 149/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9187 - loss: 0.2117 - val_accuracy: 0.9312 - val_loss: 0.2097
Epoch 150/150
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9125 - loss: 0.2302 - val_accuracy: 0.9312 - val_loss: 0.2120

Training complete! ✅
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8950 - loss: 0.2223
Loss value :0.2223125845193863
Accuracy Value: 89.50%

Predictions on Test Data (First 20 Samples)

In [10]:
predict = model.predict(X_test)

headers = f'{'#':<4} {'Age':>4} {'Age':>8} {"Prob":>8} {'Actual':>10}{'Predict':>10}'
print(headers)
print("-" * len(headers))

X_org = pd.DataFrame(
    scaler.inverse_transform(X_test),
    columns=df.drop(columns=["Heart Disease"]).columns
)

for i in range(20):
  row = X_org.iloc[i]
  prob = predict[i][0]
  gender = "Male" if row["Gender_Male"] == 1 else "Female"
  pred_label   = "Heart Disease 😟"     if prob >= 0.5    else "Happy 😇"
  actual_label = "Heart Disease 😟"     if y_test[i] == 1 else "Happy 😇"
  print(f"{i:<4} {row[0]:>5.0f} {gender:>8} {prob:>8.4f}  {actual_label:>12}  {pred_label:>12}")

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
#     Age      Age     Prob     Actual   Predict
------------------------------------------------
0       77   Female   0.9737  Heart Disease 😟  Heart Disease 😟
1       42     Male   0.1213       Happy 😇       Happy 😇
2       42   Female   0.0568       Happy 😇       Happy 😇
3       40   Female   0.1210       Happy 😇       Happy 😇
4       78   Female   0.9290  Heart Disease 😟  Heart Disease 😟
5       40   Female   0.0218       Happy 😇       Happy 😇
6       49   Female   0.0682       Happy 😇       Happy 😇
7       43     Male   0.2068       Happy 😇       Happy 😇
8       62     Male   0.6144  Heart Disease 😟  Heart Disease 😟
9       64     Male   0.5608       Happy 😇  Heart Disease 😟
10      68     Male   0.9398  Heart Disease 😟  Heart Disease 😟
11      61     Male   0.6126  Heart Disease 😟  Heart Disease 😟
12      78   Female   0.0560       Happy 😇       Happy 😇
13      65   Female   0.9671  Heart Disease 😟  Heart Disease 😟
14      48   Female   0.5908       Happy 😇  Heart Disease 😟
15      57   Female   0.4572       Happy 😇       Happy 😇
16      60     Male   0.9742  Heart Disease 😟  Heart Disease 😟
17      56     Male   0.7365  Heart Disease 😟  Heart Disease 😟
18      50   Female   0.3061       Happy 😇       Happy 😇
19      43     Male   0.0264       Happy 😇       Happy 😇

/tmp/ipykernel_1719/3708668650.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"{i:<4} {row[0]:>5.0f} {gender:>8} {prob:>8.4f}  {actual_label:>12}  {pred_label:>12}")

In [11]:
custome_sample = np.array([
[75,228,119,66,1,8,119,1,1,0,0,1,0,0,1,0,0,1,0,1,0,1,0,0,1,0],
[53,234,91,67,3,5,196,1,0,1,0,1,0,0,0,0,1,1,0,0,1,1,0,0,1,0],
[77,309,110,73,0,4,122,1,0,1,1,0,0,0,0,0,1,1,0,1,0,0,1,0,1,0],
[64,211,105,86,8,2,120,1,1,0,0,0,0,1,0,1,0,1,0,0,1,0,1,0,1,1],
[60,208,148,83,4,2,113,1,1,0,1,0,0,0,0,0,1,0,1,1,0,0,1,0,1,0],
[63,204,141,68,8,3,107,1,0,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1,0,1],
[67,282,108,87,3,9,85,1,1,0,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,0],
[67,325,177,81,8,10,192,1,0,1,0,0,1,0,0,0,1,0,1,0,1,1,0,0,1,1],
[60,226,168,99,8,10,97,1,0,1,0,0,1,0,0,0,1,0,1,0,1,0,1,1,0,1],
[74,298,148,70,9,8,157,1,1,0,0,0,1,0,0,1,0,1,0,0,1,0,1,0,1,0]
])

persons = [index+1 for index,value in enumerate(custome_sample)]

custome_sample_scaled = scaler.transform(custome_sample)

custom_pred = model.predict(custome_sample_scaled)

print(f"Heart Disease Probability")
print(f"{'Person':>5} {'Probability':>14} {'Status':>15}")
print("-" * 40)

for label, prob in zip(persons, custom_pred):
    status =  "Heart Disease 😟"  if prob >= 0.5  else "Happy 😇"
    print(f"{label:>5} {prob[0]:>14.4f} {status:>15}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
Heart Disease Probability
Person    Probability          Status
----------------------------------------
    1         0.6421 Heart Disease 😟
    2         0.4785         Happy 😇
    3         0.9979 Heart Disease 😟
    4         0.7792 Heart Disease 😟
    5         0.1062         Happy 😇
    6         0.3992         Happy 😇
    7         0.9863 Heart Disease 😟
    8         0.9692 Heart Disease 😟
    9         0.0630         Happy 😇
   10         0.9776 Heart Disease 😟